db:
  IP: 192.168.2.106
  user: maxthemule
  password: teradatarocks  
  targetDatabase: "MULE"
  targetTable: "FAST_IMPORT"
kafka:
  bootstrapServer: localhost:9092
  topic: quickstart-events