db:
  IP: 192.168.2.105
  user: maxthemule
  password: teradatarocks  
  targetDatabase: "MULE"
  targetTable: "FAST_IMPORT"
kafka:
  bootstrapServer: 172.30.71.233:9092
  topic: quickstart-events